PARENTS_NAME = 'mom and dad'        # you and your partner's name
BABY_NICKNAME = 'peanut'            # your nickname for the incoming baby
LABOR_PHRASE = 'itshappening.gif'   # the secret phrase to POST to send text notifications
BORN_PHRASE = 'babyisborn'          # the secret phrase to POST to send text and phone call notifications
NUMBER = '+13338675309'             # your twilio phone number
PORT = 1234                         # the port your app will run on
URL = 'http://yoursite.com'         # the callback url for phone calls
SID = 'yourtwiliosid'               # your twilio sid
AUTHTOKEN = 'yourtwilioauthtoken'   # your twilio auth token
